# Generated by Django 4.1.7 on 2024-09-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(verbose_name='応募日')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('application_route', models.CharField(max_length=100, verbose_name='応募経路')),
                ('document_selection_pass_date', models.DateField(blank=True, null=True, verbose_name='書類選考通過日')),
                ('first_interview_date', models.DateField(blank=True, null=True, verbose_name='1次面接実施日')),
                ('first_interview_note', models.TextField(blank=True, null=True, verbose_name='1次面接メモ')),
                ('second_interview_date', models.DateField(blank=True, null=True, verbose_name='2次面接実施日')),
                ('second_interview_note', models.TextField(blank=True, null=True, verbose_name='2次面接メモ')),
                ('offer_date', models.DateField(blank=True, null=True, verbose_name='内定通知日')),
                ('offer_note', models.TextField(blank=True, null=True, verbose_name='内定通知メモ')),
                ('offer_acceptance_date', models.DateField(blank=True, null=True, verbose_name='内定承諾日')),
                ('offer_acceptance_note', models.TextField(blank=True, null=True, verbose_name='内定承諾メモ')),
                ('job_position', models.CharField(max_length=100, verbose_name='募集職種')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('region', models.CharField(max_length=100, verbose_name='地域')),
                ('skills', models.TextField(verbose_name='スキル')),
                ('desired_joining_date', models.DateField(blank=True, null=True, verbose_name='入社希望時期')),
                ('current_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='現年収')),
                ('desired_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='希望年収')),
                ('offered_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='提示金額')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
            ],
        ),
    ]
