# Generated by Django 4.1.7 on 2024-09-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='selection_phase',
            field=models.IntegerField(choices=[(0, '応募'), (1, '書類選考'), (2, '1次面接'), (3, '2次面接'), (4, '内定')], default=0, verbose_name='選考フェーズ'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='selection_status',
            field=models.IntegerField(choices=[(0, '未処理'), (1, '選考OK'), (2, '選考NG'), (3, '調整中'), (4, '日程確定'), (5, '内定通知'), (6, '内定承諾'), (7, '入社'), (8, '辞退')], default=0, verbose_name='選考ステータス'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='現年収'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='desired_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='希望年収'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='offered_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='提示金額'),
        ),
    ]
