# Generated by Django 4.1.7 on 2024-09-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_flow', '0002_applicant_selection_phase_applicant_selection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='casual_meeting_date',
            field=models.DateField(blank=True, null=True, verbose_name='カジュアル面談実施日'),
        ),
    ]
