# Generated by Django 4.1.7 on 2024-09-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_flow', '0003_applicant_casual_meeting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='費用発生日')),
                ('description', models.CharField(max_length=255, verbose_name='費用の内容')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='費用額（円）')),
            ],
        ),
    ]
